### ISSUE TITLE
Automatically add every new issue to "janus-idp planning" project

### ISSUE THREAD

**Issue by kadel** [janus-idp/.github#28]
To make planning easier, we want to ensure every issue is in the "janus-idp planning" project.

Right now, I can see two options for how this can be done.
1) create a GitHub action (in .github repo) that will be triggered periodically (nightly should be ok) that scans through all issues in all repos in this org that are not in the project (or that were created since the last run) and adds them to the project
2) github action that will be triggered on issue creation on each repo

benefit of 2) is that it will be quicker, but downside is that will be a separate action for each repo ([workflows can be reused](https://docs.github.com/en/actions/using-workflows/reusing-workflows), so this will be defined in one place 

benefit of 1) is that everything will be in one place but a bit slower (nightly)

Acceptance criteria:
- every new issue created in any repo in this org is automatically added to "janus-idp planning"

**Comment by Zaperex** [comment]
For 2), I think we can just create a reusable workflow and place it in the .github repository, and have it only trigger when called by another workflow. 

I was initially thinking of having it only trigger when you label an issue with `status/triage` which would always happen if an issue is created with one of the generic templates.

**Comment by kadel** [comment]
> I was initially thinking of having it only trigger when you label an issue with `status/triage` which would always happen if an issue is created with one of the generic templates.

If this always happens, I wouldn't complicate it with the extra conditions and just trigger it for every created or reopened issue. 
I forgot to mention reopening in the original description. But this is also important, as we could have an issue that gets closed and removed from the project, and then for some reason, it gets reopened. In this case, we want to track it in the project in the same way as the new issue.

**Comment by Zaperex** [comment]
Sure I think it'll make sense for newly created issues to be added, but would we  really need the reopening to trigger this as well? Currently when an issue is closed, it doesn't get removed from the project, so having it trigger on reopen would cause the action to unnecessarily trigger when it doesn't need to. Would that be an issue?
